trigger: none

variables:
  feedGUID: 'fa77312d-d5d2-4152-afd1-fd786ea0b953'
  feedName: 'AdaFeed'

  major: '0'
  minor: '1'
  revision: $[counter(variables['minor'], 0)] #this will get reset when minor gets bumped. The number after Counter is the seed number (in my case, I started at 1).
  app_version: '$(major).$(minor).$(revision)'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Npm@1
    inputs:
      command: install
      workingDir: $(Build.SourcesDirectory)
      verbose: false
      customCommand: 'version $(app_version) --no-git-tag-version --allow-same-version'
    displayName: 'npm install'

  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: $(Build.SourcesDirectory)
      verbose: false
      customCommand: 'run build-lib:prod'
    displayName: 'create production build for library'

  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: $(Build.SourcesDirectory)
      verbose: false
      customCommand: 'run postbuild-lib:prod'
    displayName: 'run postbuild script for library'

  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: $(Build.SourcesDirectory)/dist/ng-payment-card
      verbose: false
      customCommand: 'version $(app_version) --no-git-tag-version --allow-same-version'
    displayName: 'set npm version'

  - task: Npm@1
    inputs:
      command: publish
      workingDir: $(Build.SourcesDirectory)/dist/ng-payment-card
      verbose: false
      publishRegistry: useFeed
      publishFeed: $(feedGUID)/$(feedName)
    displayName: 'npm publish'
